language: java

services:
  - mysql

notifications:
  email:
    recipients:
      - ephemeralin@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

before_install:
  - mysql -e 'CREATE DATABASE _360;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('6EgM3zX6EE') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart

after_success:
  - bash <(curl -s https://codecov.io/bash)
